### ISSUE TITLE
When will the code be released?

### ISSUE THREAD

**Issue by synsin0** [PKUVDIG/DrivingGaussian#1]
Thanks for your first work of GS in AD!

**Comment by PKUVDIG** [comment]
Thank you for your interest. The codes and models will be released after
the paper gets accepted.



[image: Mailtrack]
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality11&>
Sender
notified by
Mailtrack
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality11&>
23/12/17
09:32:20

Yining Shi ***@***.***> 于2023年12月14日周四 10:10写道：
